# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1eb05bf48abed35a3ec9fb44ee3399cf2b80192b44c53dc6d50a21c69e16caa00bbaa8b7535fac09666f3538713b28d933e5caa415339b6f4d3e4ad606a3da3

test:
  secret_key_base: aa25b220a618b35d59b55657d4484baf097a18fe7f583aed1429d6ba42df11a0a11a34c43281eb7f31d3ab48b2c978f6a264a53cc75655513435deb0b1c56bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
